### ISSUE TITLE
While inserting i got below error

### ISSUE THREAD

**Issue by thackerronak** [GetStream/node-restify-mongo-api#1]
{
  "message": "Cannot use 'in' operator to search for '_id' in {\n    \"task\": \"new moves1\",\n    \"status\": \"pending\"\n}\n"
}

**Comment by dwightgunning** [comment]
I can replicate this by setting the content-type header to 'text/plain'. Try 'application/json' and you should be fine.

**Comment by dwightgunning** [comment]
Just merged 73928cc86c3c918166913c37c803fbca12400ae8 which validates content-type header on post and put requests.
